SELECT 
`S`.`URL` AS SERVERURL,
`SO`.`NAME` AS SONAME,
`SOS`.`NAME` AS SERVICENAME,
`SOS`.`RETURNTYPE` AS SERVICERETURNTYPE,
`SP`.`PARAM1`,
`SP`.`PARAM2`,
`SP`.`PARAM3`,
`SP`.`PARAM4`,
`SP`.`PARAM5`
FROM `SERVERS` S
JOIN `SO` SO ON SO.IDSERVER = S.IDSERVER
JOIN `SOSERVICES` SOS ON SOS.IDSO = SO.IDSO
JOIN `SERVICESPARAMS` SP ON SP.IDSERVICE = SOS.IDSERVICE
JOIN `SOOWNER` SOO ON SOO.IDOWNER = SO.IDOWNER
WHERE `SOO`.`USER` = ?
AND `SOO`.`PASSWORD` = ?
ORDER BY 
SERVERURL,
SONAME,
SERVICENAME,
SERVICERETURNTYPE,
PARAM1,
PARAM2,
PARAM3,
PARAM4,
PARAM5