SELECT  `SO`.`IDSMARTOBJECT`, `SO`.`IDSOZIGBEE`, `SO`.`SERVERURL`,
        `CA`.`NAME`, `SER`.`IDSERVICESO`, `SER`.`NAME`, `P`.`NAME`, `P`.`TYPE`,
        `P`.`MINVALUE`, `P`.`MAXVALUE`, `P`.`OPTIONS`
FROM `SODB`.`USER` U
JOIN `SODB`.`SOUSERJOIN` SOUJ ON `SOUJ`.`IDUSER` = `U`.`IDUSER`
JOIN `SODB`.`SMARTOBJECT` SO ON `SO`.`IDSMARTOBJECT` = `SOUJ`.`IDSMARTOBJECT`
JOIN `SODB`.`CATEGORY` CA ON `CA`.`IDCATEGORY` = `SO`.`IDCATEGORY`
JOIN `SODB`.`SERVICE` SER ON `SER`.`IDCATEGORY` = `CA`.`IDCATEGORY`
JOIN `SODB`.`SERVICEPARAMETER` SERPAR ON `SERPAR`.`IDSERVICE` = `SER`.`IDSERVICE`
JOIN `SODB`.`PARAMETER` P ON `P`.`IDPARAMETER` = `SERPAR`.`IDPARAMETER`
WHERE `U`.`USERNAME` = 'username'
ORDER BY    `SO`.`IDSMARTOBJECT`,
            `SER`.`IDSERVICE`,
            `P`.`IDPARAMETER`